(map load '("services.arc"
            "state.arc"
            "strings.arc"
            "queue.arc"
            "pprint.arc"
            "code.arc"
            "html.arc"
            "srv.arc"
            "app.arc"
            "prompt.arc"
            "news.arc"))
